qrcode:
  path: #

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qrcode?useSSL=false&allowPublicKeyRetrieval=true
    username: "prac"
    password: 1234
    initialization-mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: #
            client-secret: #
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
