qrcode:
  path: /Users/park/Documents/study/QRCodeGenerator/src/main/resources/static/QRCode/

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qrcode?useSSL=false&allowPublicKeyRetrieval=true
    username: "prac"
    password: 1234
    initialization-mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 849215442642-u6b8pnpe4sdrf92k6iribsr2u3djd0lb.apps.googleusercontent.com
            client-secret: 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
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
